# Generated by Django 4.2.20 on 2025-03-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhead',
            name='info_from_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='info_from_number',
        ),
        migrations.AddField(
            model_name='familyhead',
            name='social_media_link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='social_media_link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
