# Generated by Django 4.2.20 on 2025-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_familyhead_info_from_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='total_family_members',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
