# Generated by Django 4.2.20 on 2025-03-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_family_total_family_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.familyhead'),
        ),
    ]
