# Generated by Django 4.2.20 on 2025-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_member_family_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='relation_with_family_head',
            field=models.CharField(choices=[('son', 'Son'), ('daughter', 'Daughter'), ('spouse', 'Spouse'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], max_length=255),
        ),
    ]
