# Generated by Django 4.2.20 on 2025-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_member_relation_with_family_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
