# Generated by Django 4.2.20 on 2025-03-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_familyhead_email_id_alter_member_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhead',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='familyhead',
            name='building_name',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='familyhead',
            name='city',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='familyhead',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='familyhead',
            name='flat_no',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='familyhead',
            name='landmark',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='familyhead',
            name='street_name',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='building_name',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='flat_no',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='landmark',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='street_name',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
