# Generated by Django 4.2.20 on 2025-03-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_familyhead_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='pincode',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='pincode',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
