# Generated by Django 4.2.20 on 2025-03-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_familyhead_pincode_member_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='native_place',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='native_place',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
