# Generated by Django 4.2.20 on 2025-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_familyhead_native_place_member_native_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='building_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='flat_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='landmark',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='native_place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='pincode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='street_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='building_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='flat_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='landmark',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='native_place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='pincode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='street_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
