# Generated by Django 4.2.20 on 2025-03-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_familyhead_building_name_alter_familyhead_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='surname',
        ),
    ]
