# Generated by Django 4.2.20 on 2025-03-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_remove_family_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='familyhead',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
