# Generated by Django 4.2.20 on 2025-03-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_familyhead_last_name_familyhead_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='social_media_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='social_media_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
