# Generated by Django 4.2.20 on 2025-04-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_alter_familyhead_social_media_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='door_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='door_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
