# Generated by Django 4.2.20 on 2025-04-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_familyhead_door_no_member_door_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
