# Generated by Django 4.2.20 on 2025-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_alter_familyhead_country_alter_member_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyhead',
            old_name='native_place',
            new_name='native_city',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='native_place',
            new_name='native_city',
        ),
        migrations.AddField(
            model_name='familyhead',
            name='native_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='native_state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
