# Generated by Django 4.2.20 on 2025-04-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_rename_native_place_familyhead_native_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='exact_nature_of_duties',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyhead',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='exact_nature_of_duties',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='relation_with_family_head',
            field=models.CharField(choices=[('husband', 'Husband'), ('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('son-in-law', 'Son-in-law'), ('daughter-in-law', 'Daughter-in-law'), ('grandson', 'Grandson'), ('granddaughter', 'Granddaughter'), ('great Grandson', 'great Grandson'), ('great granddaughter', 'Great Granddaughter'), ('father-in-law', 'Father-in-law'), ('mother-in-law', 'Mother-in-law')], max_length=255),
        ),
    ]
